#!/bin/bash
set -e

# Copied from PHP image: first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- php "$@"
fi

# Defaults to an app server
role=${CONTAINER_ROLE:-app}

echo "Container role: $role"

if [ ${APP_ENV} != "local" ]; then
    php artisan config:cache
    php artisan route:cache
fi

if [ "$role" = "boot" ]; then
    exec php artisan app:boot
elif [ "$role" = "worker" ]; then
    # Temporary until Worker command supports memory option
    echo "memory_limit = 400M" >> /usr/local/etc/php/php.ini
    exec php artisan queue:work --verbose --delay=5
elif [ "$role" = "scheduler" ]; then
    while [ true ]
    do
        # We sleep, to simulate, as crontab does, running every minute
        sleep 60
        exec php artisan schedule:run --verbose --no-interaction &
    done
else
    # Execute command specified on container
    exec "$@"
fi
